# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        /post/:title

# Setup
title:            "Minh Anh"
description:      "don't be sad"
url:              http://minhanh811.github.io
baseurl:          "/"

author:
  name:           "Minh Anh"

# Custom vars
# twitter:        https://twitter.com/tybenz
github:         https://github.com/minhanh811
